#!/usr/bin/env python3

# Replacement menu dialog for exiting the desktop
# SIGTERM for a Jarvice init, halt for a systemd

# python36-gobject is required on CentOS 7 to install PyGObject

import os
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk


# Using both methods to hopefully get the result on any setup
def do_shutdown(self):
    os.system('/usr/bin/sudo kill -s TERM 1')
    os.system('/usr/bin/sudo halt --force')


class DialogWindow(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self, title="Exit")

        self.set_border_width(6)

        button = Gtk.Button(label="Exit")
        button.connect("clicked", self.on_button_clicked)

        self.add(button)

    def on_button_clicked(self, widget):

        print("Exit requested, calling shutdown")
        do_shutdown(self)


win = DialogWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
