#!/bin/bash -e
[ -d /home/${JARVICE_ID_USER} ] || /usr/lib/JARVICE/tools/nimbix_desktop/setup-nimbix.sh
[ $$ -ne 1 ] && exec sudo -E -H -u ${JARVICE_ID_USER} "$@"

if [ "$1" = "/sbin/init" ]; then
	echo ""
	echo "/sbin/init specified, saving command line ..."
	shift
	echo "$@" >/etc/JARVICE/cmdline
	echo "Executing /sbin/init ..."
	exec /sbin/init		# XXX: doesn't seem to work in Docker
fi

NVINST=/usr/lib/JARVICE/NVIDIA/nvidia-installer
if [ -x "$NVINST" ]; then
	echo ""
	echo "Executing $NVINST ..."
	"$NVINST" -a -s --no-kernel-module -b --no-rpms --no-recursion \
		--no-nvidia-modprobe --no-install-vdpau-wrapper \
		--no-check-for-alternate-installs --no-nouveau-check \
		--no-unified-memory
fi

if [ ! -d /home/${JARVICE_ID_USER}/.ssh ]; then
	echo ""
	echo "Establishing SSH trust for user ${JARVICE_ID_USER} (to itself)..."
	sudo -H -u ${JARVICE_ID_USER} ssh-keygen -q -N "" </dev/zero \
        >/dev/null 2>&1
	sudo -H -u ${JARVICE_ID_USER} cp /home/${JARVICE_ID_USER}/.ssh/id_rsa.pub \
		/home/${JARVICE_ID_USER}/.ssh/authorized_keys
	chmod 600 /home/${JARVICE_ID_USER}/.ssh/authorized_keys
	cat <<EOF >/home/${JARVICE_ID_USER}/.ssh/config
Host *
StrictHostKeyChecking no
EOF
	chown ${JARVICE_ID_USER}:${JARVICE_ID_USER} \
        /home/${JARVICE_ID_USER}/.ssh/config
	chmod 600 /home/${JARVICE_ID_USER}/.ssh/config
fi

echo ""
echo "Executing $* as ${JARVICE_ID_USER} ..."
sudo -E -H -u ${JARVICE_ID_USER} "$@" &
wait $!
exit $?

